version: '2.4'
services:
  web:
    container_name: selbyfamily-web
    build:
      context: .
      dockerfile: Dockerfile
      target: web-production
    restart: always
    environment:
      VIRTUAL_HOST: www.selby-family.co.uk
      LETSENCRYPT_HOST: www.selby-family.co.uk
      LETSENCRYPT_EMAIL:
  redirect:
    container_name: selbyfamily-redirect
    image: morbz/docker-web-redirect
    restart: always
    environment:
      VIRTUAL_HOST: selby-family.co.uk
      LETSENCRYPT_HOST: selby-family.co.uk
      LETSENCRYPT_EMAIL:
      REDIRECT_TARGET: www.selby-family.co.uk

networks:
  default:
    name: selbyfamily
