on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to remote server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rickselby-web-server/actions/server-certificate@main
        with:
          CA: ${{ secrets.LINODE_CA }}
          CLIENT_CERT: ${{ secrets.LINODE_CLIENT_CERT }}
          CLIENT_KEY: ${{ secrets.LINODE_CLIENT_KEY }}
      - uses: rickselby-web-server/actions/docker-compose-deploy@main
        with:
          COMPOSE_FILE_PATH: docker-compose.production.yml
          CONNECT_CONTAINERS: nginx-proxy
          STACK_NAME: selbyfamily
        env:
          DOCKER_HOST: ${{ secrets.LINODE_HOST }}
          DOCKER_TLS_VERIFY: 1
          LETSENCRYPT_EMAIL: ${{ secrets.LETSENCRYPT_EMAIL }}
